### ISSUE TITLE
Advanced Search fields need wrap for long entries

### ISSUE THREAD

**Issue by allanaaa** [omeka/Omeka#1006]
I imported items from a site that has some really long collection titles. (Presumably also an issue for long exhibit titles.)

On Advanced Search, many of the themes deal with this really well. Here are the ones that need some kind of width constraint:

Berlin
![berlin-search](https://user-images.githubusercontent.com/28012148/229853801-a6baf661-634c-4194-b5a1-901e42030727.PNG)

Emiglio
![emiglio-search](https://user-images.githubusercontent.com/28012148/229853804-59487b7b-cf68-484c-aafc-5ff47761b17e.PNG)

Foundation
![foundation-search](https://user-images.githubusercontent.com/28012148/229853806-f6052b4a-34cb-4f78-a206-260f9778a7f5.PNG)

Minimalist
![minimalist-search](https://user-images.githubusercontent.com/28012148/229853809-dbbf1508-2a30-4797-a196-02bdd389f73c.PNG)

Rhythm
![rhythm-search](https://user-images.githubusercontent.com/28012148/229853810-1584b1cb-f8a8-4cde-967f-2e1124a50203.PNG)

Seasons
![seasons-search](https://user-images.githubusercontent.com/28012148/229853812-554702a3-85df-4700-a2b2-bc074497ffb8.PNG)

It would be nice if there was a one-stop solution in core, but I'm guessing this is a theme-by-theme issue. Sorry for the compound issue!

**Comment by zerocrates** [comment]
Core _can_ provide styles out to the themes now, though I don't know if it makes sense to do so in this situation.

**Comment by kimisgold** [comment]
@allanaaa I think I've addressed all the affected themes, and they should be ready for testing.

**Comment by allanaaa** [comment]
Fantastic, everything looks great. 

Only one other thing to note:

In Berlin, the Exhibits plugin adds an advanced search field inconsistent with the other fields. It doesn't make a difference visually in any other theme, but in Berlin they end up side-by-side instead of label on top of field. 

![berlin-exhibit](https://user-images.githubusercontent.com/28012148/230186620-b35b2db3-46ac-444c-9167-553a1275bb54.PNG)

Probably the code in the Exhibits plugin needs to be changed rather than the theme? The exhibit field has this extra `div class="two columns alpha"` and then some extra classes (`five columns omega`) on the `inputs` div that the other ones don't have. Seems to be the columns, two, and five that are having unintended effects.

```
        <div id="search-by-public" class="field">
        <label for="public">Public/Non-Public</label>        <div class="inputs">
        <select name="public" id="public">
    <option value="">Select Below </option>
    <option value="1">Only Public Items</option>
    <option value="0">Only Non-Public Items</option>
</select>        </div>
    </div>
    
    <div id="search-by-featured" class="field">
        <label for="featured">Featured/Non-Featured</label>        <div class="inputs">
        <select name="featured" id="featured">
    <option value="">Select Below </option>
    <option value="1">Only Featured Items</option>
    <option value="0">Only Non-Featured Items</option>
</select>        </div>
    </div>

    <div class="field">
    <div class="two columns alpha">
        <label for="exhibit">Search by Exhibit</label>    </div>
    <div class="five columns omega inputs">
        <select name="exhibit" id="exhibit">
    <option value="">Select Below </option>
    <option value="1">Exhibit: A Groat's Worth of  Wit for a Penny</option>
```

**Comment by zerocrates** [comment]
We should probably just fix that in Exhibit Builder.

**Comment by kimisgold** [comment]
I've just updated Exhibit Builder to address this. I noticed Geolocation fields were doing the same thing, so they've gotten the same fixes.

**Comment by allanaaa** [comment]
That's fixed it, thanks!
