### ISSUE TITLE
Error reporting on installation form.

### ISSUE THREAD

**Issue by ponchio** [omeka/Omeka#1009]
Got the cryptic error in the installation form:

There were errors found in your form. Please edit and resubmit.

And could not figure what the error was. So I updated the install/views/scripts/index/index.phtml to report the errors:

```
<p><?php echo __('There were errors found in your form. Please edit and resubmit.'); ?></p>
     <?php $errors = $this->form->getMessages();
    foreach($errors as$field=>$error) { ?>
    <p><?php echo $field.': '.current($error)?></p>
	<?php } ?>
```

$errors is an array like this: ['password' => ['passwordTooShort' => 'Password needs to be at least 6 characters in length']]

This would help new users. Didn't want to make a PR, someone can just copy and adapt this 4 lines of code.

**Comment by zerocrates** [comment]
This is actually a regression from the new theme introduced in version 3.0. The install form is supposed to display those error messages next to the form fields that they apply to.

I made a fix that restores that behavior.
