### ISSUE TITLE
Pagination navigation needs unique landmark name

### ISSUE THREAD

**Issue by kimisgold** [omeka/Omeka#1030]
Even though we provide an `aria-label` for our pagination element, accessibility audit tools are flagging it because the label is not unique. This is what we currently have.

`<nav class="pagination-nav" aria-label="<?php echo __('Pagination'); ?>">`

This is the error I see.

<img width="669" alt="image" src="https://github.com/omeka/Omeka/assets/606764/c867b780-a5db-4c67-8042-5ca4ec5b5128">

**Comment by zerocrates** [comment]
possibilities: mark the second pagination as aria-hidden? its duplication maybe isn't really useful for screenreader users. and if hidden it doesn't need the label

**Comment by kimisgold** [comment]
That works. It for sure reduces the number of landmarks a screenreader would have to navigate.

**Comment by zerocrates** [comment]
I think hidden is going to be dicey: it's going to be ignored or cause problems depending on the platform if the contents are tab-focusable, and making them all non-focusable then makes them not tabbable for anyone. So I don't know that that's going to be a workable option.
