### ISSUE TITLE
_log() not logging

### ISSUE THREAD

**Issue by patrickmj** [omeka/Omeka#385]
_log() is not logging. Am I missing something new?

 Here's  .htaccess

```
# Remember to enable display_errors on development environments only.
<IfModule mod_php5.c>
    php_value display_errors 1
    php_flag register_globals off
</IfModule>

RewriteEngine on
SetEnv APPLICATION_ENV development
# If know that mod_rewrite is enabled, but you are still getting mod_rewrite errors,
# uncomment the line below and replace "/" with your base directory.
# RewriteBase /
```

and config.ini

```
;;;;;;;;;;;;;
; Debugging ;
;;;;;;;;;;;;;

; debug.exceptions
; Throw exceptions for bad URLs.
; default: false
;
; This should only be enabled when debugging or developing for Omeka.
debug.exceptions = true

; debug.request
; Dump data about each web request to the browser.
; default: false
;
; The request data shows what routes and variables Omeka has parsed from
; each request.
debug.request = false
```

**Comment by JialuZhang** [comment]
@patrickmj 

In your posted configuration,
```
RewriteEngine On
```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
