### ISSUE TITLE
Consider making add_translation_source part of Omeka_Plugin_AbstractPlugin::setUp()

### ISSUE THREAD

**Issue by patrickmj** [omeka/Omeka#561]
It seems like we have a pretty solid and stable practice for building translations and keeping them in a regular place.

To promote regularity across plugins, we could put a check for the existence of a `languages` directory and `.mo` files within it into the abstract class's `setUp()` method. This would remove a mechanical step from plugin-building if we establish that `.mo` files go in `languages`, which I think we're pretty much at.

When we document how to do i18n (and yes, we will! :) ) that'd also build in a coherence between documentation and practice.

**Comment by zerocrates** [comment]
This kind of change probably doesn't make sense at this point in Classic's lifecycle.
