### ISSUE TITLE
Whitespace isn't trimmed when inviting users by e-mail

### ISSUE THREAD

**Issue by ssimpkin** [omeka/Omeka#654]
The "Invite A New User" feature throws the following error when there's additional whitespace at the end of the invited user's e-mail address (at least in omeka.net):

> Invited user email: Invalid hostname given for email address. 'gmail.com ' appears to be a DNS hostname but cannot match TLD against known list 'gmail.com ' does not appear to be a valid local network name

Suggest trimming whitespace from the e-mail address upon form submission to avoid this issue.

**Comment by zerocrates** [comment]
"Invite a New User" is an interface that's specific to omeka.net, so it doesn't actually exist in this codebase.

If you haven't yet, send your suggestion through Omeka.net's contact form: http://info.omeka.net/contact/

**Comment by ssimpkin** [comment]
Will do, thanks!
