### ISSUE TITLE
Quick Filter View All doesn't work?

### ISSUE THREAD

**Issue by amandafrench** [omeka/Omeka#658]
Have tested on a couple of separate Omeka 2.2.2 sites, and in the Items admin browse (admin/items/browse) the "Quick Filter --> View All" doesn't change the number of items showing. The other Quick Filters seem to work (Public, Private, Featured).

**Comment by zerocrates** [comment]
I think this is just be a confusion over terms: "View All" is just a quick filter for "no filter," getting you back to the regular paginated view of all items. It's not intended to change the page limit.

**Comment by zerocrates** [comment]
You *can* add `per_page=-1` to the query string if you're a logged-in admin. In current versions you can only do this on the Items page, but in 2.3 you'll be able to on any browse page. We probably wouldn't want to put that right in the interface though, as it would take forever and/or fall over if you've got a hefty number of items.

**Comment by amandafrench** [comment]
Oh, my bad, I assumed it meant View All items in the database on one page. Which, yes, I figured was not to be undertaken lightly with lots of items. Thanks for the clarification.
