### ISSUE TITLE
omeka_search_texts MyISAM question

### ISSUE THREAD

**Issue by misilot** [omeka/Omeka#661]
Hi,

I want to place my Omeka instance into a MariaDB Galera Cluster, however it only supports InnoDB for replication. Would the search stop working if I change omeka_search_texts to InnoDB instead of MyISAM?

Thanks!

**Comment by zerocrates** [comment]
MariaDB appears to support FULLTEXT indexes on InnoDB on version 10.0.5 
and up. If you have a current-enough version of MariaDB, you should be 
able to switch to InnoDB and have the search continue working.

**Comment by misilot** [comment]
Thanks @zerocrates
