### ISSUE TITLE
Test 2.3.1

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#671]
Use the latest master branch.

* Check upgrade (you should be prompted to upgrade the database when you move from 2.3 to 2.3.1)
* Check the "Tags" admin page: tags with counts of 0 should appear (if you remove a tags from the item edit and no other items are using it anymroe)
* Test file thumbnailing with the Imagick strategy to confirm it's working properly (Imagick is installed on omekadev if you need a server that has the extension)

**Comment by mebrett** [comment]
What should I give as the ImageMagick directory path in settings for an install on Dev?

**Comment by zerocrates** [comment]
It should just be /usr/bin on dev.

If you're using the imagick strategy by editing config.ini, it doesn't matter what path you use.

**Comment by mebrett** [comment]
Tags with a use count of 0 definitely show up (many more than I anticipated). 
Now that I've got the right derivative strategy, thumbnailing seems to be working for jpg, png, mov, pdf, mp3

**Comment by mebrett** [comment]
Orientation issues with PDFs as well as images using imagic. See: http://dev.omeka.org/mebrett/Omeka/items/show/4
