### ISSUE TITLE
Check for DOM extension in installer

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#673]
It's not infrequently missing and it's required by Zend Framework's current versions. See: 

http://omeka.org/forums/topic/add-first-item
http://omeka.org/forums/topic/problems-with-222-installation

**Comment by zerocrates** [comment]
@patrickmj do you recall any other of these kinds of posts but for different missing dependencies? I vaguely think there were some but have no specific recollection of what they might have been. It's trivial for us to check for extensions on install though.

**Comment by patrickmj** [comment]
I can't recall any. There was a guy at C4L surprised by needing ant, hence java, to build from a git pull, but that seems different
