### ISSUE TITLE
Omeka and Php 7

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/Omeka#676]
Hi,

Zend 1.12 has been made compatible with php 7. Is this planned for Omeka 2? This means only to remove all deprecated features, if any. Main advantages are the speed, that will be two times faster and the memory two times lower.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by zerocrates** [comment]
As long as Zend Framework 1 works with 7, then Omeka should as well. The support policy has been to make Omeka work with all PHP versions above its minimum, and that should continue with 7.

I'll look into enabling the CI tests to run on the 7 prerelease builds (as we're already doing for S).

**Comment by Daniel-KM** [comment]
Hi,

Fine. I didn't check a nude Omeka, so I'm going to update some plugins.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by zerocrates** [comment]
We've updated Zend Framework to a version that officially supports PHP 7, and we're running our automated tests on it as well, so I'm marking this as closed.
