### ISSUE TITLE
Our getID3 version is broken on PHP 7

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#677]
> PHP Fatal error:  'break' not in the 'loop' or 'switch' context in application/libraries/getid3/getid3.lib.php on line 285

This looks like it's resolved in newer versions of getID3. The downside is that any versions higher than what we have now only support PHP 5.3 and up, so we'd have to either raise Omeka's minimum to match or skip any usage or loading of getID3 on 5.2.

**Comment by patrickmj** [comment]
For hosting companies, 5.3 shouldn't be a problem, if I remember right from that spreadsheet we put together. Hard to know impact on people's own servers (like ours).

Would that change warrant bumping Omeka to version 2.4?

**Comment by zerocrates** [comment]
I think there's some disagreement about whether changing requirements like that affects the major/minor version, but yes, I'd tend to say that a change like that would make most sense in a 2.4, not a 2.3.2

**Comment by patrickmj** [comment]
Much agreed. It'd be a good signal for everyone to check the requirements before upgrading.

**Comment by Daniel-KM** [comment]
Hi,

Php 5.2 is no more supported by php and other cms are gradually made compatible with php7. 

If the only issue for php7 is getId3, a warning during the installation or upgrade will be enough. It's just a copy of a library to put in the folder "libraries" and eventually a warning in the system page to remember it.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by zerocrates** [comment]
I definitely think we should upgrade to getID3's latest (side note, that does make the tests pass cleanly, though that says as much about the coverage of the tests as it does Omeka's compatibility), I'm just unsure as to whether it makes more sense to selectively disable getID3 or to bump up our version requirement.

Bumping the version would theoretically let us use some more tools and libraries than are currently available to us (like Composer, for one), but we'd have to gin up something to check the version on upgrade and prevent it for sites running on 5.2, and of course there's some marginal loss of users who can't or won't upgrade. 

The main factors pushing me to increase are that PHP 5.3 is *really* old already (let alone the ancient husk of 5.2), and not only is it EOL'd, but even 5.4 is as well.

**Comment by zerocrates** [comment]
Things we might want to use and their requirements:

- Composer (5.3.2, 5.3.4 recommended)
- password_compat (5.3.7, though some distros have backported necessary changes to earlier versions)
- Pheanstalk (5.3.0)

Zend Framework and HtmlPurifier both maintain 5.2 compatibility.

Composer would be nice to have, but we do have a lot of stuff that currently uses Zend's old include_path-based autoloading to handle things like the plugins
