### ISSUE TITLE
/api/files paging and api_key behavior

### ISSUE THREAD

**Issue by minorg** [omeka/Omeka#679]
Using Omeka 2.3, a request to /api/files without an API key returns the first page of objects. Subsequent requests for additional pages (1, 2, 3...) returns the same, first page of objects. It took me a while to figure out what was happening. Surely (1) the request without an API key should be rejected and/or (2) a request for page 2+ should return no results?

**Comment by patrickmj** [comment]
Thanks for the report. My first thought is that (2) is the greater issue. For (1), if a file is publicly accessible on the site, it should be accessible via the API without a key. We'll have to see what's up with the pagination. Could you give us the details of the request to the API you are making?

**Comment by zerocrates** [comment]
Yeah, I can't reproduce this, at least not in the obvious method. Whether or not I set per_page, I get different results when i change the page parameter, and eventually just an empty array when I page too far.

**Comment by minorg** [comment]
I'm unable to reproduce the pagination issue now that I've fixed other parts of my script, so I'd say it's a false alarm, and the problem was on my side. I apologize.

I wasn't aware that you could use the API without a key.

Feel free to close this issue.

**Comment by zerocrates** [comment]
No problemo
