### ISSUE TITLE
Test media changes

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#682]
Test on latest master

The default media embed for audio and video is now the HTML 5 audio and video tags.

* This needs to be tested across browsers and platforms
* We also want to test a reasonably broad range of formats:
  * Audio:
    * .mp3 should work everywhere
    * .wav should work everywhere but IE
    * .aac or .m4a audio should work most places
    * other audio formats (.ogg, .opus, etc.) may be interesting to see results but aren't as necessary, they probably work on Chrome and Firefox only
  * Video:
    * modern .mp4 video (H.264) should work everywhere
    * _old_ .mp4 video (or old .mov) should fail pretty much everywhere, ideally falling back to a link
    * there's no other format that's as ubiquitous for video, but .webm and .ogv (Theora) should work on Chrome and Firefox
* As much as possible, when audio/video doesn't work in a browser, we should be presenting a plain link
  * Some formats had their support removed and should _never_ try to show a player on any browser: for audio this is MIDI, for video this is mostly old MPEG-1/2 video (.mpeg, .mpg, .m1v, .m2v)
  * Other formats just have spotty support but the browsers that can't play it should fall back to showing a link: wav on IE, .aiff anywhere but Safari, webm or ogv on IE or Safari
* Other general things:
  * Nothing should autoplay
  * Comments/examples about things that don't work well or as expected on any browser/format combination are welcome

**Comment by zerocrates** [comment]
Further notes:

This should obviously be tested without any media plugins like HTML5 Media enabled, but this change also shouldn't affect those kinds of plugins when they *are* enabled, they should still work as before.

It's possible that we might be able to generate thumbnails, or pick the "video" or "audio" fallback thumbnail, for files, yet still not be able to show the player. That's expected, and the thumbnails really just depend on what imagemagick supports on that particular server.

**Comment by zerocrates** [comment]
This goes beyond strictly testing, but this is probably a good time to create a manual page talking specifically about the media formats we work with, to make some suggestions at least for things that should work well.

**Comment by zerocrates** [comment]
It might be worth it to look at .avi, .wma, .wmv also. Those are currently unchanged, meaning as always we do an embed that basically only works on IE. We could remove that, dropping them back to links everywhere. The result is a slightly worse experience (maybe) for IE, but quite likely a better experience everywhere else.

**Comment by mebrett** [comment]
Quick notes on other formats - worked as expected, when file unplayable the browser either downloaded the file or asked me if I wanted to download or open with Quicktime.

AVI (http://dev.omeka.org/mebrett/Omeka/items/show/1039): Chrome, Firefox, and Safari all gave me a message indicating a missing/unsupported plugin. 

WMA (http://dev.omeka.org/mebrett/Omeka/items/show/1041): as with AVI (missing plugin message) but the message was cut off into a long thin rectangle. 

WMV (http://dev.omeka.org/mebrett/Omeka/items/show/1042): File is represented by what I assume is the first frame of the video; clicking on it downloads the file for all 3 browsers.

**Comment by zerocrates** [comment]
The WMA one is basically as expected, it uses a thin rectangle because that's (roughly) the size of the audio controls that _would_ be there if the browsers supported the plugin

WMV is interesting. Clearly ImageMagick is able to read that file and give you a thumbnail, but it's somewhat surprising to me that we're actually showing that thumbnail there.

**Comment by zerocrates** [comment]
Okay, so, you're getting the WMV result because that's the default display option: what we use when we either can't tell what the file is or don't have anything configured to show that kind of file. That's somewhat surprising to me as I think we have a .wmv mapping, but I'll look into it.

Regardless, that's a good way to see what will happen if we take out the AVI/WMA display code too, they'll display the same way as just a link (using a thumbnail if ImageMagick can make one).

**Comment by zerocrates** [comment]
Yeah, for whatever reason, we don't look at ".wmv" for display purposes, so WMVs only get the player embed if they happen to be detected as the mime type we're expecting.

I'm leaning more and more toward the right answer being to remove the AVI/WMV/WMA display code entirely, since it works in so few places.

**Comment by mebrett** [comment]
*I'm leaning more and more toward the right answer being to remove the AVI/WMV/WMA display code entirely, since it works in so few places.*

That makes sense to me - it would be more legible to the user if they displayed as a link (since they're generally unplayable)

**Comment by zerocrates** [comment]
@mebrett Can you re-test AVI, WMV, and WMA now? The code that tries to show the player is gone now.

**Comment by mebrett** [comment]
WMV is still showing the screencap of the first frame, but AVI and WMA are now just displaying as a download link.

**Comment by zerocrates** [comment]
Okay, that's as expected.

Final verdict on the media stuff?

**Comment by mebrett** [comment]
At this point I would say everything is working as expected.
