### ISSUE TITLE
Add OR support in items advanced search

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#705]
WIP branch is advanced-search-or.

Obviously missing some UI/UX stuff like reflecting the AND/OR in the filters output and hiding/disabling the AND/OR select for the first row, and of course just styling generally to make it fit.

Most importantly, needs feedback on whether results conform to users' expectations for what an AND/OR selector will do.

**Comment by luku** [comment]
Hi,
for me the *joiner* like this works perfectly fine. I'm also very interested in this feature, so I wonder if there is something I could help with to make it into stable version sooner?

Perhaps one thing related to displaying the current search filters - should we show the used *joiner* for advanced criteria? E.g. 

> Title is not empty **and** Description is empty **or** Description contains X

? If yes, I could do it, if it helps...

**Comment by zerocrates** [comment]
I just have to get back to this and some things like styling and other related polish (and making sure we're not breaking pre-existing stuff that composes searches and doesn't know about the joiner).

Showing the joiners in the "current filters" display is definitely part of that and something we'll need to do to make that display accurate.
