### ISSUE TITLE
Paginating items in collections#show views

### ISSUE THREAD

**Issue by duhaime** [omeka/Omeka#709]
Hi all, I'm writing with a quick question: how can one create and display pagination links in the collections#show view? I posted to the Omeka forms, but it seems like there is a bit of automated bot activity over there, so I wanted to follow up with a thread here as well in case the boards aren't monitored.

I'm getting started with Omeka, and am looking to paginate the items within the show method of the collections controller, but seem to be overlooking something. I manually set the results per page in the admin view to 10. After doing so, there were only 10 records displayed on the collections#show page, as expected. However, the collections#show url doesn't contain any pagination params, and manually adding them doesn't seem to alter the records returned or displayed. Also, my call to `<?php echo pagination_links($options = array()); ?>` in collections#show didn't display any pagination elements in the view.

After sifting through the Omeka codebase a little, it seemed like the `browseAction()` function in the AbstractActionController sets the pagination values in the ZendRegistry, but the `showAction()` in the AbstractActionController does not. On a whim, I tried manually setting some dummy paginate values in the ZendRegistry from the collections#show view page (!), and was happy to see the pagination divs populated in the view.

How would your team recommend adding pagination to the collections#show view? In case you're curious, I'm working on the code base here: https://github.com/YaleDHLab/ani-yun-wiya and have my development instance running here: http://ec2-52-40-96-18.us-west-2.compute.amazonaws.com/omeka/collections/show/2?page=1

I would be very grateful for any insights you can offer!

**Comment by zerocrates** [comment]
Let's stick with the forum thread on this one.

The forums are monitored, it's just that they sometimes get snowed under with spam posts in a very short period of time (particularly around major sporting events for whatever reason).
