### ISSUE TITLE
Shortcodes might not be able to handle large IDs

### ISSUE THREAD

**Issue by patrickmj** [omeka/Omeka#711]
A shortcode like

`
[items ids=23096]
`
gets an error that no item has been assigned to the view, after the data get passed along to `single.php`

but this works

`
[items ids=23]
`

I've confirmed that both items actually exist.

**Comment by zerocrates** [comment]
Hmm that's a strange one. 23,096 isn't really large enough to be likely causing any problems.

**Comment by patrickmj** [comment]
And yet, the same SimplePage with a shortcode, 23 works, 23096 breaks:

`
exception 'Omeka_View_Exception' with message 'A current item variable has not been set to this view.' in /var/www/ChroniclingAmerica/application/views/helpers/GetCurrentRecord.php:27
Stack trace:
#0 [internal function]: Omeka_View_Helper_GetCurrentRecord->getCurrentRecord('item')
#1 /var/www/ChroniclingAmerica/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#2 /var/www/ChroniclingAmerica/application/views/helpers/Metadata.php(53): Zend_View_Abstract->__call('getCurrentRecor...', Array)
#3 /var/www/ChroniclingAmerica/application/views/helpers/Metadata.php(53): Omeka_View->getCurrentRecord('item')
#4 [internal function]: Omeka_View_Helper_Metadata->metadata('item', 'Collection Name', Array)
#5 /var/www/ChroniclingAmerica/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#6 /var/www/ChroniclingAmerica/application/libraries/globals.php(2038): Zend_View_Abstract->__call('metadata', Array)
#7 /var/www/ChroniclingAmerica/application/libraries/globals.php(2038): Omeka_View->metadata('item', 'Collection Name', Array)
#8 /var/www/ChroniclingAmerica/themes/berlin/items/single.php(10): metadata('item', 'Collection Name')
#9 /var/www/ChroniclingAmerica/application/libraries/Omeka/View.php(117): include('/var/www/Chroni...')
#10 /var/www/ChroniclingAmerica/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/var/www/Chroni...')
#11 /var/www/ChroniclingAmerica/application/libraries/Zend/View/Helper/Partial.php(109): Zend_View_Abstract->render('items/single.ph...')
#12 [internal function]: Zend_View_Helper_Partial->partial('items/single.ph...', Array)
#13 /var/www/ChroniclingAmerica/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#14 /var/www/ChroniclingAmerica/application/views/helpers/Shortcodes.php(235): Zend_View_Abstract->__call('partial', Array)
#15 /var/www/ChroniclingAmerica/application/views/helpers/Shortcodes.php(235): Omeka_View->partial('items/single.ph...', Array)
#16 [internal function]: Omeka_View_Helper_Shortcodes->shortcodeItems(Array, Object(Omeka_View))
#17 /var/www/ChroniclingAmerica/application/views/helpers/Shortcodes.php(81): call_user_func('Omeka_View_Help...', Array, Object(Omeka_View))
#18 [internal function]: Omeka_View_Helper_Shortcodes->handleShortcode(Array)
#19 /var/www/ChroniclingAmerica/application/views/helpers/Shortcodes.php(64): preg_replace_callback('/\[(\w+)\s*([^\...', Array, 'The winner for ...')
#20 [internal function]: Omeka_View_Helper_Shortcodes->shortcodes('The winner for ...')
#21 /var/www/ChroniclingAmerica/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#22 /var/www/ChroniclingAmerica/plugins/SimplePages/views/public/page/show.php(20): Zend_View_Abstract->__call('shortcodes', Array)
#23 /var/www/ChroniclingAmerica/plugins/SimplePages/views/public/page/show.php(20): Omeka_View->shortcodes('The winner for ...')
#24 /var/www/ChroniclingAmerica/application/libraries/Omeka/View.php(117): include('/var/www/Chroni...')
#25 /var/www/ChroniclingAmerica/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/var/www/Chroni...')
#26 /var/www/ChroniclingAmerica/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('page/show.php')
#27 /var/www/ChroniclingAmerica/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('page/show.php', NULL)
#28 /var/www/ChroniclingAmerica/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#29 /var/www/ChroniclingAmerica/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#30 /var/www/ChroniclingAmerica/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#31 /var/www/ChroniclingAmerica/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#32 /var/www/ChroniclingAmerica/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#33 /var/www/ChroniclingAmerica/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#34 /var/www/ChroniclingAmerica/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#35 /var/www/ChroniclingAmerica/application/libraries/Omeka/Application.php(77): Zend_Application->run()

`

**Comment by zerocrates** [comment]
Looks like that's a custom items/single.php.

My guess would be something implemented incorrectly in there, quite likely the call to get the collection name. My guess would be that 23096 is in a collection and 23 is not.

**Comment by patrickmj** [comment]
thanks. good point. will look there.
