### ISSUE TITLE
Collections don't have link to output formats

### ISSUE THREAD

**Issue by patrickmj** [omeka/Omeka#717]
While generally I'm in favor of making showing output formats optional, since they're there, and plugins can add output formats to Collections pages, there should be a link to get to them.

Example from VRA Core plugin: add a collection with VRA core data (down a couple levels to get it recognized for now). Adding `output=vra` to the end of the show URL gives some VRA XML, but the link isn't shown.

**Comment by zerocrates** [comment]
Do I remember correctly that you actually added this?

**Comment by patrickmj** [comment]
yep. https://github.com/omeka/Omeka/commit/ee26a5e54c8ae1b77d1ebc2ed256d58143d92208
