### ISSUE TITLE
Move off of the old TinyMCE branch

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#731]
This caused some issues when we tried it before, but we should take another look.

**Comment by zerocrates** [comment]
Changes don't seem to be particularly significant: largely different config setting names, a different name for the script itself, and some styling issues because they're not using an iframe anymore. The commands for adding and removing editors are also changed, which could be an issue.

What we need to make an informed decision is a solid list of the plugins that use the editor. We can paper over the changes within the core to some extent, but seeing what plugins are actually doing will tell us whether there's any point to do so (if say, they're using `mceAddControl` which is gone, they'll need a code change no matter what so there's no point to us shifting around the config keys to make things work as expected).

**Comment by patrickmj** [comment]
Commenting is biggest one I know of. I'm pretty sure it uses `mceAddControl` when you hit the 'reply' link, which creates a new comment input form

**Comment by zerocrates** [comment]
We've got at least:

- obviously the core itself (no problem as we'll update it along with the change)
- Exhibit Builder (ditto, as it's bundled)
- Simple Pages (ditto again)
- Commenting (problematic as it's non-bundled and also doesn't use the "normal" code for using the editor, so it certainly needs a separate update)
- Guest User (but not really, seems to be dead code)
- Simple Contact Form (on the admin side)
- Contribution (on the admin side)
