### ISSUE TITLE
Call to undefined function filter_var()

### ISSUE THREAD

**Issue by PisikeSipelgas** [omeka/Omeka#736]
Hi, 

https://my.domain.com/omeka/admin/appearance/edit-navigation
Apache and php are configured to write errors to file.

Add a Link to the Navigation: Enter "Label", Enter "URL", hit "Save Changes" and blank page appears .
Into error log file is written:
Sep  6 20:06:51 hostname httpd: PHP Fatal error:  Call to undefined function filter_var() in /paht/to/omeka/application/libraries/Omeka/Navigation/Page/Uri.php on line 109

**Comment by zerocrates** [comment]
You need the PHP extension `filter` installed. It's usually installed by default, but if you're managing the installation yourself you might need to install some additional package to get it.

**Comment by PisikeSipelgas** [comment]
Hi, 
That did the trick!
Thanks!
