### ISSUE TITLE
Mysqli statement execute error Column 'added' cannot be null

### ISSUE THREAD

**Issue by hklish01** [omeka/Omeka#741]
I have Neatline installed. When I try to create a new exhibit I'm getting the following error message.  I don't know if this is a Neatline error or an Omeka error.

Zend_Db_Statement_Mysqli_Exception
Mysqli statement execute error : Column 'added' cannot be null

There was an older Omeka forum message related to this exact error but I'm not sure I understand how to fix it in my installation. http://omeka.org/forums-legacy/topic/neatline-error-11

Any help is appreciated.

exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in ../omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:

0 ../omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
1 ../omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
2 ../omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
3 ../omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
4 ../omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
5 ../omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
6 ../omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
7 ../omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
8 ../omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
9 ../omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
10 ../omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
11 ../omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
12 ../omeka/application/libraries/Omeka/Application.php(79): Zend_Application->run()
13 ../omeka/admin/index.php(28): Omeka_Application->run()
14 {main}

**Comment by zerocrates** [comment]
I was about to point you to the new forums topic about this, but that's you, isn't it?

This is a Neatline issue so it's really more properly reported on Neatline's issue tracker: https://github.com/scholarslab/Neatline/issues

I had thought this was already reported there, but I don't immediately see an issue for it, so they may be unaware of the problem (these date-based problems often only pop up for certain server environments).

As for the old forum post, the file they're talking about needing to change in Neatline is in the models/abstract folder.

**Comment by hklish01** [comment]
Ok, I will.  Thanks!
