### ISSUE TITLE
What about fluid layout for admin section?

### ISSUE THREAD

**Issue by luku** [omeka/Omeka#742]
I consider the default max-width 960px of grid layout based on _skeleton.css_ in admin section way too small.
So I wonder if there are any plans to support fluid or wider layouts for larger screens (>1200px)?
I found 2 sites with possible solution:
1. [grid for fixed width 1280px](https://webdesign.tutsplus.com/tutorials/building-a-responsive-layout-with-skeleton-widescreen--webdesign-7473) 
2. [fluid grid for screen wider than 1200px](http://visualculture.me/skeleton-grid-fluid/)
Anything interesting?

**Comment by zerocrates** [comment]
I think the concern here is for how things, particularly plugins, might have been designed with the current (and now longstanding) layout in mind.

I understand the desire for more horizontal space, especially as resolutions have crept upward, but it just adds more combinations of things that need to be tested. I wouldn't rule out widening as a possibility, but I imagine just a wider fixed width breakpoint at the largest step is more likely/feasible than a much more sweeping change to a totally fluid layout.

**Comment by zerocrates** [comment]
Done!
