### ISSUE TITLE
Admin Pagination Issue

### ISSUE THREAD

**Issue by ShariqT** [omeka/Omeka#745]
The template setting for pagination is not being honored. I have this set for 25 for the admin and public side. On the admin side, it only shows one item and/or collection at a time.

**Comment by ShariqT** [comment]
Also, it seems that editing rights have been locked down to only the people who have originally created the collection.

**Comment by zerocrates** [comment]
Can you show a screenshot?

You might be encountering an error displaying the page and a screenshot would show this (for example, the footer would be missing).

**Comment by ShariqT** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/735544/19195833/2e510260-8c81-11e6-8453-f7aa6f68d479.png)

**Comment by ShariqT** [comment]
I'm sorry. This was due to php-xml not being loaded on the server. I'm closing this now.

**Comment by zerocrates** [comment]
Yes, this is definitely not a pagination problem per se, but an error that's happening when that first row is getting rendered (notice there's no footer and nothing in the "Date Added" column).

Try following the "Display Error Messages" instructions on [this documentation page](https://omeka.org/codex/Retrieving_Error_Messages), and we should be able to see what the actual error that's happening is.

**Comment by zerocrates** [comment]
Oops, I missed your message in between.

If you did see an error, could you share what it was? We have a previous issue up about making it more clear that the "dom" extension is required, so this would just be more evidence that we have to get that fixed to avoid people having these kinds of problems.
