### ISSUE TITLE
Allow search for items not in a collection

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#746]
See https://forum.omeka.org/t/how-do-i-find-all-items-not-in-a-collection/1857/2

**Comment by Daniel-KM** [comment]
Hi,

See https://github.com/omeka/Omeka/pull/693 too.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by zerocrates** [comment]
Yes, thanks. I'd forgotten about that one.

This and that should work nicely together.
