### ISSUE TITLE
Untranslatable part in Exhibit builder plugin

### ISSUE THREAD

**Issue by MarulkAF** [omeka/Omeka#748]
there seems to be an untranslatable string in the ExhibitBuilder plugin in:
/views/helpers/ExhibitFormAttachments.php: line 31

`$html .= '<div class="add-item button">Add Item</div>';`

change to:

`$html .= '<div class="add-item button">'. __('Add Item') .'</div>';`

**Comment by zerocrates** [comment]
Can you send this, or a pull request making the change you mention, to the [ExhibitBuilder issue tracker](https://github.com/omeka/plugin-ExhibitBuilder/issues) instead? It's really an ExhibitBuilder-specific issue, and that's the place for those.
