### ISSUE TITLE
Add option to themes to allow choice between link to file/show view or directly to file

### ISSUE THREAD

**Issue by kalbers** [omeka/Omeka#759]
Right now items/show on themes uses files_for_item() which spits out direct links to the files themselves. Might be useful to add an option in the themes to alternatively mirror the admin side behavior which loops through the files and uses link_to_file_show to provide links to the file show page.

This would make it easier for users to expose file metadata if they have entered it, and make it possible on .net, where it is currently not.

**Comment by zerocrates** [comment]
I believe this is also possible just in `files_for_item`: pass `linkToMetadata => true` to link to the files/show page.
