### ISSUE TITLE
Test new advanced search boolean options

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#766]
This is all item-specific advanced search stuff, on master.

In particular, look at the AND/OR selector for:
- results matching what you expect (the interesting cases are usually items that have multiple values for a single Element)
- visual correctness with the new elements for selecting and showing the boolean conjunctions
- behavior (the AND/OR appearing and disappearing correctly when the number of advanced search rows changes, an existing search filling in the form correctly when you click the advanced search link to edit it)

**Comment by Daniel-KM** [comment]
Hi,

When there are more than 10 advanced statements, mysql freezes.

Sincerely,

Daniel Berthereau
Indodoc & Knowledge management

**Comment by zerocrates** [comment]
@Daniel-KM

Hmm... I'll see if I can reproduce. I wonder if that's not just a preexisting issue related to the length of the query, not a new problem introduced by this feature. Or just a consequence of doing many unavoidably slow "contains" searches.

**Comment by mebrett** [comment]
@zerocrates I'm not clear on the expected behavior of "an existing search filling in the form correctly when you click the advanced search link to edit it" - does this mean if I already have text in the general search bar and click down to Advanced Search without deleting that text, it should populate in "Search for Keywords"?

**Comment by zerocrates** [comment]
Keywords isn't really touched in 2.5 at all, and it's not related to the general search bar anyway. This is only about the item-specific search, and this part specifically about the "Search Items" button on the items browse

The "existing search" part means this: you do an item advanced search, filling in whatever fields, and go see the results. Clicking the "Search Items" link from those results should prefill everything from the search you just did. In particular, we want to confirm that it fills in the new AND/OR stuff correctly.

**Comment by zerocrates** [comment]
@Daniel-KM what version of MySQL server are you using?

It seems this might be a known problem where MySQL takes a really long time just to run the query optimizer on queries with many joins (so even an EXPLAIN takes basically the same time). Setting `optimizer_search_depth = 0` (telling it to automatically determine how exhaustive to be in the optimizer) in my.cnf drastically improved the performance for me.

**Comment by mebrett** [comment]
One thing I've noticed is that on the admin side the first "Narrow by specific fields" looks like the old advanced search, and only subsequent fields have the AND/OR dropdown.  On public view, by contrast, the AND/OR dropdown shows up for the first iteration of Narrow by Specific Field (true across themes)

Admin:
![screen shot 2016-12-08 at 1 18 43 pm](https://cloud.githubusercontent.com/assets/2314070/21021962/dc4eb018-bd48-11e6-8691-6b8dfca3870a.png)

Public:
![screen shot 2016-12-08 at 1 18 18 pm](https://cloud.githubusercontent.com/assets/2314070/21021965/df91cda0-bd48-11e6-9d10-44b7cade0022.png)

**Comment by zerocrates** [comment]
That's a bug on the public side, since that first AND/OR doesn't actually have an effect, so it's purposely hidden from the first entry.

**Comment by mebrett** [comment]
Existing search populating with current terms when you click "Search Items" works on the admin side but no on the public side.

**Comment by zerocrates** [comment]
I think that's a preexisting bug but it's good to note.
