### ISSUE TITLE
New advanced search includes first and/or on the public side

### ISSUE THREAD

**Issue by mebrett** [omeka/Omeka#767]
Via #766 On public view of the themes, the new And/Or dropdown shows up for the first "Narrow by Specific Field" option. That first AND/OR doesn't have an effect, so it should be hidden.

**Comment by zerocrates** [comment]
Unlike S, all the themes handle the basic styling of the advanced search form themselves, so I think this has to involve changes to all the themes.

@kimisgold I did this on the admin side with first-of-type hiding and adjustment of percentage widths. The themes don't do quite the same styling for this form that the admin does but I assume basically the same thing should work for them as well.

**Comment by kimisgold** [comment]
@mebrett Can you test the fixes for this across the themes?

**Comment by mebrett** [comment]
This is fixed across all themes (Berlin, Center Row, default/Thanks Roy, Emiglio, Minimalist, Rhythm, Santa Fe, Seasons, The Daily)
