### ISSUE TITLE
Fix all the whitespace crud

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#769]
Rather than continually carping at pull requests for messing with whitespace, let's just actually remove all the wrong whitespace we've got floating around already in one fell swoop, and require whitespace to be correct from then on.

Best to just deal with the current system for 2.5 then do this after the release, I think.

**Comment by patrickmj** [comment]
Guessing that you'll just run php-cs-fixer to automatically fix everything? If so, should we note the settings here and run it on plugins, too?

**Comment by zerocrates** [comment]
Yes, I'll probably just use php-cs-fixer (deciding whether to have it go beyond just whitespace though).

If it's anything significant, I'll probably have it checked in to the repository so we can run in on the automated tests like in S.
