### ISSUE TITLE
Test unsaved-warning branch

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#774]
The branch adds the same unsaved changes warning feature as exists in S.

The main thing we need here is a runthrough of different forms/pages (including those from plugins) to make sure that the feature is working as expected, including both that it correctly detects pending changes when they exist and correctly *doesn't* report changes when nothing has been changed.

The feature is only on the admin side.

**Comment by mebrett** [comment]
It worked pretty much as expected on Chrome and Firefox. I noticed that if you're creating an exhibit and go to make a page, the notification doesn't fire but the changes are automatically saved.

I am having trouble getting it to work in Safari. As long as I click "stay on page",  I keep getting the warning. But once I click "leave page," the warnings stop. Safari seems to think once I've said no, I mean no for the entire site, not just that instance.

**Comment by zerocrates** [comment]
My investigation so far leads me to the conclusion that it's an unworkaroundable Safari bug:

- http://www.openradar.me/28814642
- https://tracker.moodle.org/browse/MDL-56465

Can you check to see if the same behavior is also happening with S? I'd like to rule out slight differences between the two as a culprit (and possibly track the issue for S too).

If it's just a Safari bug we won't be able to do much about it but we can at least be aware of the problem.

**Comment by mebrett** [comment]
Confirmed that it also happens in Safari for Omeka S.

**Comment by mebrett** [comment]
Only one other note - if you edit an item or collection and then, without saving, try to delete, you get the unsaved changes message *after* confirming delete. If you click "leave" it goes ahead and deletes the item (thus leaving with unsaved changes) but the order of events is a little confusing. (This may simply be something to note in end user documentation)

**Comment by mebrett** [comment]
In testing IE I found one bug that I've confirmed on Chrome and Firefox. On /admin/appearance/edit-navigation if you *only* change nav depth (by dragging and dropping) but not nav order, item titles, or anything else, then the unsaved changes warning does NOT trigger.
