### ISSUE TITLE
Admin panel navigation overlaps content at wider screen width

### ISSUE THREAD

**Issue by jeremyboggs** [omeka/Omeka#776]
At a wider viewport size, the left-hand content navigation overlaps the content container slightly:

<img width="494" alt="omeka-admin-content-nav" src="https://cloud.githubusercontent.com/assets/48310/22429533/e501f030-e6d8-11e6-86b2-d730ca8c9beb.png">

Seems the [content-nav's width in 1200min.css](https://github.com/omeka/Omeka/blob/master/admin/themes/default/css/media/1200min.css#L10) is slightly wider than the left-padding the content div [inherits from skeleton.css](https://github.com/omeka/Omeka/blob/master/admin/themes/default/css/skeleton.css#L68)

On Omeka.2.5.

**Comment by zerocrates** [comment]
Does that persist after a hard refresh?

The left margin at 1200+ isn't in the section of skeleton.css you linked, but lower down in a section of overrides for the specific sizes.

**Comment by jeremyboggs** [comment]
It did, but it seems to be an issue with my browser. (Hard refreshing isn’t actually working.)

Tried it on a different browser without issue. Should have done that first. Closing.
