### ISSUE TITLE
Omeka.warnIfUnsaved - tinyMCE + HTMLPurifier problem

### ISSUE THREAD

**Issue by luku** [omeka/Omeka#779]
Warning about unsaved changes appears, even though no changes were made. It applies to all pages where tinyMCE appear and the submitted data are filtered by HTMLPurifier.

Steps to repro:
1. Goto Settings > Security and make sure HTML filtering is enabled (checked) or enable it
2. Create new Item, choose any field you want, check "Use HTML" checkbox and create numlist or bullist
3. Save changes and directly edit same item again
4. Try to refresh page or navigate away - warning appears

I spent some time debugging and the problem is that HTMLPurifier is stripping new line after `<ol>` or `<ul>`, while tinyMCE is always trying to prettify the HTML. So the original text is never same as soon as tinyMCE is loaded and the warning appears.
Example:
- in tinyMCE:
```html
<ol>
<li>one</li>
<li>two</li>
</ol>
```
- in DB (after submit of tinyMCE field):
```html
<ol><li>one</li>
<li>two</li>
</ol>
```

I don't have any good idea how to fix it yet. Changes in purifier or tinymce doesn't feel good at all... Any ideas?

**Comment by zerocrates** [comment]
This no longer seems to be an issue, likely because of the update to TinyMCE in the meantime.
