### ISSUE TITLE
Testing for 2.5.1

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#801]
Use the "stable-2.5" branch.

Points of interest are:
- the upgrade process: there are several fixes here, but all that's to be done testing-wise is just to upgrade install(s) and confirm that it doesn't break (ideally coming from a few different versions but don't worry too much about this if inconvenient)
- Delete links from the user browse: these go to a new page in 2.5 and that page is broken. In 2.5.1, they should show a popup which should work, middle-click or "open in a new tab" should get you the separate page, which should also work.
- Using 2.5.1 should fix the "unfollowable links in mobile public side nav" problem

**Comment by mebrett** [comment]
Reference for the "unfollowable links in mobile public side nav"? (forum or issue?)

**Comment by zerocrates** [comment]
Uh, that is the one that @kimisgold was working on a week or so ago, the problem that only came up on touchscreen desktops? (and mobile, incidentally)

I don't have a link immediately to hand.

**Comment by mebrett** [comment]
Initial testing has delete user working from the browse page again (Safari, Chrome, Firefox). I upgraded a site from 2.4 with no issues. 

Top-level links clickable on mobile with the bundled themes; if we want to double-check on a touch-screen laptop I think I know someone who has one.
