### ISSUE TITLE
UTF-8 support for snippet() function

### ISSUE THREAD

**Issue by luku** [omeka/Omeka#805]
Hi,
I noticed [snippet()](https://github.com/omeka/Omeka/blob/master/application/libraries/globals.php#L2879) function in `globals.php` cannot handle correctly multibyte strings. I'd like to ask before doing pull request - which encoding-aware methods would you prefer?
1. mb_* family
2. iconv_* family

And if we choose mb_* family, isn't it good idea to place `mb_internal_encoding('UTF-8')` call inside bootstrap?

Thanks,
Luk

**Comment by zerocrates** [comment]
I want to say mbstring is the better option, and it's probably better to just specify the encoding in each mb_ function call rather than mess with mb_internal_encoding. You might need to check for the existence of the extension, too.
