### ISSUE TITLE
Item - Method named getElements() does not exist

### ISSUE THREAD

**Issue by luku** [omeka/Omeka#808]
Hi,
I noticed the overloaded method [getElements()](https://github.com/omeka/Omeka/blob/master/application/models/Item.php#L76), when accessing `Item->Elements`, is not defined anywhere. Is it bug or old code that wasn't removed yet?
And if it should be kept, what does it suppose to return? All elements from DC + ITM set, belonging to current item? And indexed by *set name* and then by *element name* in same format as `Item->getItemTypeElements()`? Or any other ideas?

**edit:** Same applies to `Collection` record as well. And there is even another undefined method [getElementText()](https://github.com/omeka/Omeka/blob/master/application/models/Collection.php#L58). Shouldn't it use `getAllElementTexts` method like for `Item` record? 
Not sure if I should open new issue for it, or if we can handle all of them here... 

Thanks,
Luk

**Comment by patrickmj** [comment]
Both Items and Collection use the mixin `ElementText`. It's in the `models/Mixins` folder.

**Comment by luku** [comment]
Yes, but those methods are not defined there either. If you try to access `Elements` property for either Item or Collection, you'll get nice `BadMethodCallException`

**Comment by patrickmj** [comment]
Huh....so it is. We'll have to dig around, but it definitely looks like code that was superceded by other approaches at some point.

**Comment by zerocrates** [comment]
`getElements` has been gone since 2.0. I'd be most inclined to just call the 'Elements' related entry cruft and remove it.

**Comment by luku** [comment]
Yeah, perhaps it's best to remove it. Those values would be cached and since ElementText mixin is already caching same info, it's not really needed. The only good usage I can think of is if you want get all elements associated with item (i.e. to add display filter for all elements). It's possible to get DC via ElementText mixin, but the item type specific elements must be fetched fresh from DB (via Item->getItemTypeElements()). Doesn't feel like much gain...

And what about `getElementText()` method for Collection record? Shouldn't it use `getAllElementTexts()` method instead like for Item?

**Comment by zerocrates** [comment]
Yes, I believe you're right there as well.

These "shortcut" related properties are in many ways a holdover from earlier design philosophies and don't always get a lot of attention (and due to their "magic" nature they can be a little more difficult to track or notice).
