### ISSUE TITLE
Left menu overlaps content div in admin theme when page width exceeds 1200px

### ISSUE THREAD

**Issue by hktang** [omeka/Omeka#812]
Just a minor layout issue, please check the screen shot below:

![Sreenshort](http://www.clipular.com/c/5982310584549376.png?k=XgLt485WODrL2a8CwWMZr4BY3Go)

Happens only when the viewport width exceeds 1200px..

**Comment by zerocrates** [comment]
Can you confirm whether this persists after clearing your browser cache (or trying in a different browser)?

We've had reports of this before, and they've been resolved by clearing the cache for those users.

**Comment by hktang** [comment]
Thanks! Clearing the cache works..
