### ISSUE TITLE
collections/show has no pagination but limits the query anyway

### ISSUE THREAD

**Issue by zploskey** [omeka/Omeka#819]
The CollectionController showAction limits the items query to the number of records that is set, using the result of `$this->_getBrowseRecordsPerPage()`. However, the show page does not have any pagination controls, and this means that collections with more items than the limit simply leave off a lot of items.

This is the offending line: https://github.com/omeka/Omeka/blob/master/application/controllers/CollectionsController.php#L45
```
        $this->view->items = $this->_helper->db->getTable('Item')->findBy(
            array('collection' => $this->view->collection->id), $this->_getBrowseRecordsPerPage());
```

There are two ways to deal with this in my estimation;
- Remove the limit, changing the call to
```
        $this->view->items = $this->_helper->db->getTable('Item')->findBy(
            array('collection' => $this->view->collection->id));
```
- Add pagination controls to the show page.

In our fork we opted to remove the limit. Let me know which sounds most reasonable and I'll submit a pull request.

**Comment by zerocrates** [comment]
Removing the limit won't work too well probably, just because collections can get _very_ large.
