### ISSUE TITLE
Update HTMLPurifier

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#821]
Among other things, the new version has support for some more CSS properties that are fairly desirable.

**Comment by patrickmj** [comment]
Are any of the new supported properties related to https://github.com/omeka/plugin-CSSEditor/issues/2

**Comment by zerocrates** [comment]
Yes, min/max width/height are newly supported in the most recent HTML Purifier versions.

**Comment by patrickmj** [comment]
awesome!

**Comment by zerocrates** [comment]
We also need an update here for PHP 7.2 support, see ezyang/htmlpurifier#154
