### ISSUE TITLE
Move link to retrieving error messages to new site

### ISSUE THREAD

**Issue by patrickmj** [omeka/Omeka#826]
Or, will a redirect do the trick?

**Comment by zerocrates** [comment]
Yes we probably should do this.

The old url will be redirected over as well, so it's not too urgent.

**Comment by patrickmj** [comment]
Additional question: The current docs say "Omeka 2.0 and newer" for the guidance. That's in the site context of Omeka Classic, but I worry that the distionction is non-obvious

http://omeka.org/classic/docs/Troubleshooting/Retrieving_Error_Messages/
