### ISSUE TITLE
Test/document admin tag interface changes

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#833]
Master branch, the admin tag browse view.

The main changes are to search, filtering, and sorting.

The sorters should now all allow you to sort either ascending or descending by clicking on them again, like other sorters in Omeka.

The search input is new but should be self explanatory.

Picking a particular record type now has the difference that it will automatically exclude "zero" results, tags that aren't used on any record of that given type. Looking at tags for Exhibits (or for Items if you've got lots of unused tags) should make this difference obvious from "All".

@luku feel free to chime in if I've forgotten an aspect of this.

**Comment by zerocrates** [comment]
For myself, I presume we'd like to fit the search into the dead space to the left of the top paginator, and probably need labels for "Sort by" and maybe a label or just separation for the record type filter.

**Comment by luku** [comment]
It feels complete. Perhaps additional things for testing:

When particular record type is chosen, search should be restricted to the respective record type. Means if I show only Item tags and do search, it should keep searching in tags used on any Item.

**Comment by mebrett** [comment]
What does the "Time" sort do? Is it most recently created? I think that function might need a clearer name.

**Comment by zerocrates** [comment]
Can you determine which it is? It's actually kind of uncertain because of the way that time is stored for tags. It would either be, in practice, the date created, or the date last used (because the dates in question are stored for every time a tag is used on a record, not when the tag is created).

**Comment by mebrett** [comment]
It seems to be recently created?

**Comment by mebrett** [comment]
Testing notes:

- We need to come up with a clearer word for "time" ("date created", unless it's too long?)
- It would be nice if the record types dropdown also indicated what’s selected. I know it’s indicated on the left side, but it doesn’t match the other inputs in the menu and there's not a lot of visual weight to the left-hand "Record Type" display.
- Clicking the number on the tag *only* works when viewing items. It does not work for all records, or for exhibits. If it stays this way, we need to update the explanatory text under "Editing Tags" to be clearer about when clicking the number will/won't work.
- deleting a tag returns to default browse (alphabetical, descending) - which is annoying if you’re trying to delete empty tags
- Success on the "search restricted by record type"

Also, I agree that the various functions and displays on the page could be better arranged. More visual weight on what kind of record type we're looking at, and on the "view all," maybe? I think search could be moved - would it be too confusing to move it to the right, under the admin-wide search?

**Comment by mebrett** [comment]
One small suggestion as I'm starting to document these changes: could we change the displayed name of the page from "Edit Tags" to "Browse Tags," to keep it in line with the item/collection/item types pages.

**Comment by mebrett** [comment]
Another suggestion: since Alphabetical is the default sort for the tags, it makes more sense to me to put it first in the row of sort options.

![screen shot 2018-01-23 at 10 20 46 am](https://user-images.githubusercontent.com/2314070/35285172-af207b82-002a-11e8-833a-6382fdc000e7.png)

**Comment by mebrett** [comment]
And to possibly move the record types dropdown away from the others, because while the first three switch (you can sort by count OR alphabet OR time), you can filter by Record Type and then sort by Count/Alphabet/Time

**Comment by kimisgold** [comment]
I've addressed most of Megan's points, but I'm stuck on what to do about the item count links—ideally, clicking the link would show you a combination of both item and exhibit results. As is, if both items and exhibits use the same tag, the user can't click through that tag to see even just the items. I don't know how to resolve this.

**Comment by mebrett** [comment]
That looks so much better, thank you Kim.
I think it's okay if the clicking doesn't work as long as we make that clear in the documentation and maybe the prompt text on the page (maybe "1. To view all items with a tag, click the number (only works in Record Type views"?)

**Comment by zerocrates** [comment]
Is the improved version supposed to look like this? Seems a bit off (Firefox/Linux).

![supposed](https://user-images.githubusercontent.com/298975/35540744-5fa78a96-0525-11e8-9c8c-aebcce45eb1e.png)

**Comment by mebrett** [comment]
On Firefox/Mac, the search button does line up with the search bar. 
![screen shot 2018-01-30 at 10 31 16 am](https://user-images.githubusercontent.com/2314070/35574774-b75ec7a8-05a8-11e8-8ce3-d24fb9a7b5b1.png)

**Comment by mebrett** [comment]
Something I just noticed is that the "search" function works but the search results display with a count of null even when the tag has items associated with it. 

On the normal browse:
<img width="353" alt="screen shot 2018-02-05 at 11 40 49 am" src="https://user-images.githubusercontent.com/2314070/35816754-8e0fe7e0-0a69-11e8-8b16-9b1781dadc05.png">

As search results: 
<img width="479" alt="screen shot 2018-02-05 at 11 40 33 am" src="https://user-images.githubusercontent.com/2314070/35816835-b78c0b76-0a69-11e8-9589-e8956c6f99f2.png">

**Comment by mebrett** [comment]
Count display issue fixed in above commit.

**Comment by zerocrates** [comment]
@mebrett nothing left here?
