### ISSUE TITLE
Test new TinyMCE

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#837]
~~~Branch is "tinymce4"~~~

Right now I want to restrict this to the core, plugins will follow.

Pages where the editor is used:

- Edit pages for:
  - items
  - collections
  - files
- Theme config form (e.g. Homepage Text)

Pretty much any form of interaction with the editor you can come up with is fair game:
- turning the HTML checkboxes on and off
- using the WYSIWYG as well as the code editor button
- how the editor reacts to changes to the viewport size
- the ability to include "interesting" tags (think iframes, objects, audio, video, note anything will have to be allowed under Security Settings first or HTML validation will need to be turned off)
- interaction with the "you have unsaved changes" warning

Obviously bugs are the key thing, but also just impressions about the change, visually or otherwise.

**Comment by zerocrates** [comment]
@mebrett for modules paralleling this change, would you prefer that be added to this issue, or separate issues for each module?

**Comment by mebrett** [comment]
I would rather have issues for each plugin which refer back to this issue, *if* and bugs that arise with TinyMCE on the plugin level are likely to have to be resolved there. Otherwise I'm fine with them being listed here along with whatever branch I should use for each plugin.

**Comment by zerocrates** [comment]
Hmmm ok, I'll ponder over that. My plan is to have all the branches uniformly be "tinymce4", which I've just pushed for Exhibit Builder.

**Comment by patrickmj** [comment]
For my part, I generally prefer different issues so that they can be assigned to me, just so I can see more easily what's on my plate.

**Comment by mebrett** [comment]
Just doing the initial testing of adding iframes/embeds to items and collections and I'm getting an error on the public side of my site: http://dev.omeka.org/mebrett/Omeka/ `exception 'InvalidArgumentException' with message 'Could not find file javascripts/vendor/tiny_mce/tiny_mce.js!' in /websites/omekadev/home/www/mebrett/Omeka/application/libraries/globals.php:1288
Stack trace:`

Current theme is Berlin and is up to date on branch master (if that matters)

**Comment by zerocrates** [comment]
The stack trace part should be helpful: this is probably a plugin that uses tinymce that's causing the error, which you can either update if there's a branch for it or deactivate if not.

**Comment by mebrett** [comment]
Thanks John - it's Commenting that's causing the error.

**Comment by patrickmj** [comment]
Commenting branch tinymce4 isn't up to snuff yet, but basics are there. Might be best to deactivate it until I've pulled all the pieces together.

**Comment by mebrett** [comment]
Everything is working - I have not yet been able to break the editor. Embedded media sometimes overflows on the admin side (passing under the right-hand options for edit/delete/save changes, etc), but I consider that expected behavior.

**Comment by mebrett** [comment]
Ex of the overflow: http://dev.omeka.org/mebrett/Omeka/files/show/3436

**Comment by zerocrates** [comment]
Oh yeah, that's fine. The looks of the stuff put into the editor don't matter so much as just that you're able to input them.

**Comment by mebrett** [comment]
As with SimplePages, toggling html off leaves the formatting in the text field - see http://dev.omeka.org/mebrett/Omeka/items/show/3666 

I feel like this is different from before - it would just revert to unformatted text.

**Comment by zerocrates** [comment]
@mebrett As with in Simple Pages, I'm pretty sure that the toggle on/off behavior is the same as it used to be: keeping the tags. You could switch back to master to reconfirm, but I'm pretty sure there's been no change.

**Comment by zerocrates** [comment]
If we have a fair amount of certainty about the core side of this, I'll probably go ahead and merge it to avoid issues with divergence complicating testing

**Comment by zerocrates** [comment]
I merged the tinymce4 branch into master, so all testing for this should use the core's master branch from now on. (the plugins are still on tinymce4 branches)
