### ISSUE TITLE
ImageMagick

### ISSUE THREAD

**Issue by 70-degrees** [omeka/Omeka#843]
I am having challenges placing a watermark  image with ImageMagick. This plugin works with a text overlay, but not with an image watermark. Your time and help are appreciated.

**Comment by zerocrates** [comment]
Which plugin are you using?

**Comment by 70-degrees** [comment]
Hi! Thanks for asking. I am using File Modify.

**Comment by zerocrates** [comment]
You'd be better off directing this at the issue tracker for that plugin then, at https://github.com/Daniel-KM/FileModify/issues
