### ISSUE TITLE
HTML5 filtering

### ISSUE THREAD

**Issue by jcmundy** [omeka/Omeka#850]
I have another project in which I want to use an HTML5 embed, but I need to use html filtering as well.  Html filtering still seems to strip the `<audio>`, etc., tags for me no matter what I put in security settings.  Is there any way to use HTML5 in the metadata fields with filtering?  Is there any plan to make that an option?  Thank you so much for your help!

**Comment by zerocrates** [comment]
Does the HTML5 Media plugin not work for what you need? It will render a text track if both a audio/video and text are loaded on the same item and share their filenames (except for extensions).

**Comment by jcmundy** [comment]
No, I'm working with the 3Play Media interactive transcript plugin.

**Comment by jcmundy** [comment]
It uses a script to connect a hosted transcript to a file hosted elsewhere through their custom embedded app.

**Comment by jcmundy** [comment]
The plugin we are using changed their export so that it renders HTML5 through an iframe, which Omeka accepts.
