### ISSUE TITLE
CRSF token related error creating API keys

### ISSUE THREAD

**Issue by avatar382** [omeka/Omeka#852]
Attempting to generate an API key from the admin menu in the route /admin/users/api-keys/ results in an error message displayed on the form: “There was an error on the form, Please try again.”

API access is enabled. Tracing through the code, the error seems to be originating in the source code file application/controllers/UsersController.php, line 312: https://github.com/omeka/Omeka/blob/master/application/controllers/UsersController.php

Reading the code, it seems like there may be an issue with a CSRF (cross site request forgery, maybe?) token not being valid. 

I tried to create an API key when logging into a brand new Incognito window, which should create a completely fresh session with no cookies or browser cache. The result is the same.

I’m testing this on the latest version of Chrome, and get the same results in macOS and Ubuntu Linux.

Are there any known workaround for this?

Thanks!
Manny Rodriguez

**Comment by zerocrates** [comment]
That check there is new in the latest bug fix version of Omeka...

We've had at least one other report that sounds like this same issue on the forums, but when I looked into that one, I wasn't able to reproduce the issue, so there's something slightly more complex at work here, it seems.

**Comment by zerocrates** [comment]
Oh, but you're on that thread also... So this is really the same instance of the issue (the same site)?

**Comment by avatar382** [comment]
@zerocrates Thank you! The issue was the I had an old version of /admin/themes/default/users/api-keys.php. 

I think what happened is that I copied the themes directory from my old codebase to the new one when upgrading, since the instance in question had a custom theme. I think this was the same instance of the issue.
