### ISSUE TITLE
Slash URLs

### ISSUE THREAD

**Issue by edsu** [omeka/Omeka#862]
I was wondering if it's possible to configure Omeka so that URLs like:

    https://archive.blackgothamarchive.org/items/show/58

would become:

    https://archive.blackgothamarchive.org/items/show/58/

I'm trying to use [wget](https://github.com/edsu/bagweb) to create a static version of an older Omeka site, and it is converting URLs like:

    https://archive.blackgothamarchive.org/items/show/58

to:

    https://archive.blackgothamarchive.org/items/show/58.html

Which means a request for the old URL will result in a 404. I guess I could get around this with a .htaccess file, but if it is possible to change the URLs to end with a slash before I created my snapshot that would help matters significantly.

**Comment by Daniel-KM** [comment]
Most of the time, the urls are created via functions `url()` and `record_url()` in the file `libraries/globals.php`, so the simplest is to modify these functions to append a slash when needed. For more change, you'll need more work.

**Comment by edsu** [comment]
Thanks very much, I'm working with an older version of Omeka where the url function is in application/helpers/Url.php ... but I think I got the fix you suggested working!
