### ISSUE TITLE
The table omeka_sessions is full

### ISSUE THREAD

**Issue by jcmundy** [omeka/Omeka#868]
We are getting an error periodically that our omeka_sessions table is full. These are not heavily used sites. Truncating the table works as a temporary solution, but we are looking to see if we can find a longer term solution.  There error lists: Uncaught Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : The table 'omeka_sessions' is full in application/libraries/Zend/Db/Statement/Mysqli.php:214

Thank you for your help.

**Comment by jcmundy** [comment]
Yes, we are running out of disk space because the table is over-full.  That's why we truncate.

**Comment by zerocrates** [comment]
What I mean is, the sessions table is typically not terribly large, especially if you've just truncated, and if your site doesn't receive much traffic. If it's truly a disk space issue and you're using say, 95% of the disk even with the table truncated, it's going to be tough to do much.

You can set `session.saveHandler = false` in application/config/config.ini to use file-based session storage instead, which could help if it's only your database storage that's constricted in this way.

**Comment by luku** [comment]
If you get several hundred thousand entries, it's probably some search bots indexing your site. If you check access log, you should see what is it. Then you can decide to block that bot in robots.txt. 
As for long term solution, I would add following directives inside `[production]` in `application/config/application.ini`
```
resources.session.gc_probability = 1;
resources.session.gc_divisor = 100;
```
It sets the probability of the session garbage collection, using this expression: gc_probability/gc_divisor. And 1/100 means, there is a 1% chance that the garbage collection process starts on each request. You can adjust the values as you see fit, see [PHP docs](http://php.net/manual/en/session.configuration.php)

Perhaps good idea to have it in Omeka core by default? Zend doesn't use PHP defaults, and from the looks of it, it disables the garbage collection completely (`application/libraries/Zend/Session.php`)

**Comment by jcmundy** [comment]
Thank you for your help.  We did get this fixed.  It was bots.
