### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by jcmundy** [omeka/Omeka#870]
I am trying to use internationalization (https://omeka.readthedocs.io/en/latest/Tutorials/i18n.html) through the Locale Switcher plugin (https://github.com/biblibre/omeka-plugin-LocaleSwitcher).  I want to add terms for the collection names, the page links in the header, as well as text on the index page.  I am having trouble with the tutorial.  Is there any more information on how this works?  

My installation only has .mo files in the application/languages/ folder.  If I create a template.base.pot and new .po files in the application/languages/ folder and then convert to .mo, will that overwrite the .mo files already in the folder?  Do I need to copy all the strings that would currently be in the .mo file into the new .po file in addition to adding new phrases?  Is application/languages/ the correct folder to put these new .pot and .po files?  Thank you so much for your help.

**Comment by jcmundy** [comment]
Thank you so much for the information.  Do you have any tips on where I would get started to create or add a plugin with my own new translations?

Would this help? https://github.com/Daniel-KM/Omeka-plugin-Translations

**Comment by zerocrates** [comment]
Yeah, you could definitely use Daniel's plugin there: it's basically already the simplest possible plugin that adds translations. So you can just create your own .po and .mo files in that plugin's languages folder, and they'll just be added onto Omeka's existing translations.

**Comment by jcmundy** [comment]
Thank you again for your help.   I have gotten the plugin with translations working for short phrases and individual words.  Longer phrases are not always translating.  Is there a particular format for getting descriptions to translate?  For example on the collections page I can get get a single word description of a collection to translate, but not a whole sentence, despite it being in the po/mo.

**Comment by zerocrates** [comment]
Hmm... do you have an example of the text that's not working and what you had in your mo/po?

Length shoudn't be a problem, but you might be having an issue with differing types of punctuation or things like that. The strings must exactly match.

**Comment by jcmundy** [comment]
Because I am currently testing how to get all this working, before implementing on a much more complex site, I started with the basic sentence ```<p>This is an example page. Feel free to replace this content, or delete the page and start from scratch.</p>``` On a simple page it translates, but on a Collection description (Collection Browse Page) it does not.  I have implemented the translation into both languages folders.  Another Collection description (just the word "Discover") does correctly translate.  
I would like to be able to translate a complex page with links `a href` as well. I have a feeling it is about navigating the punctuation correctly.  Thank you for your help.

**Comment by Daniel-KM** [comment]
You should use poedit or a similar tool to create your po file and to convert into mo. To make it manually is hard, because there are some characters to escape and a small whitespace can break your translation.

**Comment by Daniel-KM** [comment]
https://poedit.net/

**Comment by zerocrates** [comment]
The actual markup on your site doesn't seem to match your po file... there's a `button` tag in your po example but not in the real markup.

Basically the rule is, if something's passed to `__()`, it needs an exact match in the .po/.mo to be translated. As Daniel says, there's rules for escaping and so on so a tool is usually the way to go, but I'm not sure that's your specific problem here.

If something's not being translated the general answer is either that there's no call to `__()` or that the strings don't match. That can happen because there's dynamic content, in which case you need to use sprintf to translate a "template" basically, or as it appears is the case here, because the strings simply don't match.

**Comment by zerocrates** [comment]
I'm going to close this as it doesn't really represent an issue with Omeka, I think...

I'd head to the forums if you want or need further discussion along these lines.
