### ISSUE TITLE
Filter(s) for image_tag()

### ISSUE THREAD

**Issue by apjmason** [omeka/Omeka#871]
This is a feature request to add a filter on the image_tag() function in the fileMarkup helper so that img attributes can be modified by plugins. 

As discussed in [this forum discussion](https://forum.omeka.org/t/modifying-html-from-item-image-to-customize-alt-text/6203/3) with @zerocrates , there is currently no theme-independent way to alter the attributes for thumbnails in browse views globally. This _is_ possible for full images on show pages using the file_markup filter, and a similar ability to override the output of all the item_image(image_tag()) calls in other views would be very helpful.

If a new filter could be added to core for the next release it would be great. Thanks!

**Comment by zerocrates** [comment]
There's a style of "filter" that just lets you completely replace the usual output of the function... but I assume here that it would actually be more useful to be able to filter the attributes directly.

**Comment by apjmason** [comment]
Yes, we'd still want the requested img tag, just with control over the output attributes.
