### ISSUE TITLE
XSS Vulnerability in 2.6.1

### ISSUE THREAD

**Issue by miralgj** [omeka/Omeka#882]
Dorkbot (https://security.utexas.edu/dorkbot) discovered a XSS vulnerability in Omeka 2.6.1 by injecting malicious code into the "tour" argument.

Example injection: http://omeka.example.com/items/show/121?tour=12%22/%3E%3Cimg%20src=x%20onerror=%22alert(150)%22%20/%3E%3C!%E2%80%94&index=4

**Comment by zerocrates** [comment]
Hmm, we don't use a "tour" GET parameter. Perhaps this is an issue in a plugin (or theme) used by the specific site that was tested?

**Comment by miralgj** [comment]
My mistake, I did not do my due diligence to confirm that this was from the core project. It actually belongs to the Curatescape plugin. I will report it to them. Thanks!
