### ISSUE TITLE
Deleting a Tag by REST API

### ISSUE THREAD

**Issue by vovchok** [omeka/Omeka#888]
When I try to delete a tag by using REST API then I receive a response with 500 code and body ```{"message":"Invalid record. Record \"Tag\" must define an ACL resource."}```. Documentation said that I should receive 204 code [(delete-tag)](https://omeka.readthedocs.io/en/latest/Reference/api/resources/tags.html#delete-tag).
It seems that the ```Tag``` model should implement the ```Zend_Acl_Resource_Interface``` interface.

**Comment by zerocrates** [comment]
Thanks for the report.

Yes, I believe you're correct.
