### ISSUE TITLE
Background php path not found at API Import Plugin under XAMPP

### ISSUE THREAD

**Issue by flow-motion** [omeka/Omeka#891]
Hey guys, 

i saw the thread 714 of tingletech - but i did not really understand what he was doing. 
my Problem: 
I installed OMEKA via XAMPP on my win10 machine to backup the Datas of an online installation via API IMPORT

Everything running so far. 
BUT when i want to start the backup i see in the plugin the following advise: 
The background.php.path in config.ini is not valid. The correct path must be set for the import to work.

I am googling for hours in the meantime - i have no idea what i have to insert in the config.ini that this background-.php can be launched. 
Anyone can help me pls`?

**Comment by zerocrates** [comment]
I believe this is the same as a (belatedly responded to) question on the forums, so closing here.
