### ISSUE TITLE
Db->insert() doesn't support insertion of more than one row at once

### ISSUE THREAD

**Issue by php4fan** [omeka/Omeka#907]
It seems that the Omeka's `Db::insert()` only allows to do queries like:
```
INSERT INTO table_name (field1, field2, field3) VALUES ('value1', 'value2', 'value3')
```

however, it doesn't provide a way to do a query like this:
```
INSERT INTO table_name (field1, field2, field3) VALUES ('value1_1', 'value1_2', 'value1_3'), ('value2_1', 'value2_2', 'value2_3'), ....
```
that is, a single `INSERT` query to insert more than one row.

**Comment by zerocrates** [comment]
Yes, the insert is single-row only. This stems from a variety of things, but probably the most relevant is that the Zend DB component Omeka builds on has the same restriction. This is very unlikely to change for Omeka Classic.

Multi-row inserts can be performed as raw SQL using the `query` method.
