### ISSUE TITLE
Table_Collection::find($id) returns null if collection is not public and user not logged in

### ISSUE THREAD

**Issue by php4fan** [omeka/Omeka#910]
I was going crazy figuring out why `Table_Collection::find($id)` was sometimes returning null with a valid `$id` and sometimes returned the expected collection. Then I figured out it returned null when I was logged in with an admin user, while it was returning null for the same id when I was not logged in. Finally I found out it's because that particular collection is not public.

I'm not even sure this is expecte behavior. Given that `find()` only finds one single record by id, it seems pretty stupid and useless to not return it if it's not public. Also, if that is by design the default, there should definitely be a way to explicitly ask for a given record regardless of its visibility to the current user.

But if that is really the expected behavior (again, with the huge design flaw of a lack of a way to bypass the filter), it's completely undocumented. Actually it's a bit funny to say that something in particular is not documented in Omeka, given that the developer documentation is practically non-existent as a whole. To call it "documentation" is in itself a stretch. Anyway, this is something reeeeeally basic and far from obvious (arguably wrong) that one needs to know about the `find()` method so it should be mentioned somewhere.

That is assuming it's by design. But again, I'm not sure.

**Comment by zerocrates** [comment]
find() as well as the various search methods and helpers (and really any "official" way you can think of to retrieve a record) all exclude results not visible to the current user, by design.

**Comment by php4fan** [comment]
> find() as well as the various search methods and helpers (and really any "official" way you can think of to retrieve a record) all exclude results not visible to the current user, by design.

1) That might be a reasonable default, but If there is not a parameter or other way to override that behavior, that makes them utterly useless.

2) As I said, the main issue is that's completely undocumented

**Comment by php4fan** [comment]
> If there is not a parameter or other way to override that behavior when needed, that makes them utterly useless

Just in case that is not completely obvious: the reason I say that is that it obliges me to use two completely different paradigms when I'm retrieving records that I intend to show to the user, and when I'm retrieving records from other purposes. In the first case, I can use `find`, `findBy` and "any 'official' way you can think of to retrieve a record"; in the second case, I guess I have to build queries from scratch in ways I can't officially think of. So I might as well forget about the former and always use the latter approach in all cases so that at least my code is consistent and reusable.

**Comment by zerocrates** [comment]
As far as "utterly useless," you might be surprised to learn that there isn't generally a clamor for avoiding this restriction... plugins usually work with just the set of resources accessible to the user. I'm actually somewhat interested to know what the particular use case here is, in fact.

I take your point on the documentation.

**Comment by php4fan** [comment]
> plugins usually work with just the set of resources accessible to the user

*usually* is the key word here.

> I'm actually somewhat interested to know what the particular use case here is

You shouldn't need an example to see the need for allwoing to explicitly overriding the restriction. The mere fact that it is conceivable that there might exist a use case which you haven't thought of (which is a standard assumption one should always make) should be enough.

My particular use case is fairly convoluted, but it should be a no-brainer to make up a simpler one.

I'm not talking about removing the restriction by default, just providing a way to circumvent it. The very instant someone wrote the code to create that restriction, the immediate next thought should have been: so now what will be the API to override it.

**Comment by php4fan** [comment]
To the unlucky handful of people around the world (if there still are any) who like me are forced to work with Omeka:

here's the pathetic **workaround I've found** for when you need to **retrieve some records regardless** of whether or not they are public:

```
// Replace 'Collections' with 'Items' or whatever kind of record you are working with
$acl = get_acl();
$currentUser = current_user();
$wasAllowed = $acl->isAllowed($this->_currentUser, 'Collections', 'showNotPublic');
$acl->allow($currentUser, ['Collections'], ['showNotPublic']); 
// ... DO YOUR QUERY HERE with find(), findBy() or whatever
if (!$wasAllowed) $acl->deny($currentUser, ['Collections'], ['showNotPublic']);
```

Of course this only covers a tiny subset of all conceivable use cases, but it was enough for mine.

There might be a more elegant solution, but given the utter lack of documentation, this is the best I could come up with by reverse-engineering the source code.
