### ISSUE TITLE
Control output of HTTPS in head_css?

### ISSUE THREAD

**Issue by sepastian** [omeka/Omeka#911]
I am running Omeka Classic inside Docker, i.e. phpfpm, Nginx, mariadb. I'm using Traefik as a proxy, which also handles redirection from HTTP to HTTPS and encryption using a Let's Encrypt certificate.

The pages are loading, but all links to assets start with `http://` instead of `https://`. The browser blocks mixed content, i.e. all assets (css, js, image, ...) are blocked.

Is there a way to control generation of links to assets? Assets are queued with `queue_*` and rendered with `head_*`. This, in turn invokes Zend's `headLink` further down the route. Is it possible to either a) force prepending asset URLs with `https://` or b) hide the scheme in the URLs generated, e.g. `//domain.com/assets/style.css`?

**Comment by zerocrates** [comment]
What version of Omeka are you using? Older than 2.6?

We made some changes in the more recent versions to improve Omeka's detection of situations when it's behind an SSL-terminating proxy; in particular the X-Forwarded-Proto header is respected. A slightly older change simply changed from absolute URLs to relative ones for assets, sidestepping the mixed-content problem altogether.

**Comment by sepastian** [comment]
Thanks for the quick reply @zerocrates. And sorry for the wait.

We are running Omeka version 2.3, pretty old.

```
$ cat -n app/bootstrap.php | grep -A 1 version
    10	// Define the current version of Omeka.
    11	define('OMEKA_VERSION', '2.3');
```
A quick fix/patch would be enough, getting rid of the `http:` in front of asset URLs would do, because the project is done and nothing will change. Where in the code could that be changed?

**Comment by zerocrates** [comment]
OK, 2.3... the simplest hack to that version would probably be modifying bootstrap.php.

The very simplest option is probably to just take the `$base_root` variable (around line 49) and manually set it to `'https'`.

**Comment by sepastian** [comment]
This did the trick, thanks for the help!
