### ISSUE TITLE
Minor issue: default fallback thumbnail not overridable

### ISSUE THREAD

**Issue by DBinaghi** [omeka/Omeka#913]
Hi.

I've developed a plugin to add extra fallback thumbnails (and types) to the repository, and also replace the original ones, using add_file_fallback_image function (after a suggestion by John, https://forum.omeka.org/t/new-fallbackimage-not-showing-up/7859/4).

Only problem: there's no way to replace the GENERIC_FALLBACK_IMAGE, defined inside the FileMarkup.php.

I know it should be possible to do it via a custom theme, but it'd be nice if the effects of add_file_fallback_image could be extended to the default image too. I suppose  the code in the FileMarkup.php file would have to be changed in order to explicitly assign an image to GENERIC_FALLBACK_IMAGE.

**Comment by zerocrates** [comment]
Yeah, it doesn't make a whole lot of sense to have only the "main" fallback not be modifyable.

Although, unless I'm mistaken, your module should also be able to just provide an alternate image like a theme could, just by placing it at `views/shared/images/fallback-file.png`

**Comment by DBinaghi** [comment]
No, you're not mistaken, that solution works. The problem is that it's not programmatically achieved: if the new fallback_file.png is in that directory, it gets loaded no matter what; with all other images, I can enable or disable them via config form options.
One could say that, if the plugin was installed and enabled, by default the new images were used, though... As I said, minor issue, but if it could be solved for a future release it would be nice.

**Comment by DBinaghi** [comment]
I've tried you solution, but unfortunately it seems not to be working from an Omeka Classic plugin.

**Comment by DBinaghi** [comment]
Found an easy solution. Opened a pull request with it. Hope this helps.
