### ISSUE TITLE
How do you determine filter order?

### ISSUE THREAD

**Issue by php4fan** [omeka/Omeka#919]
Gosh the documentation sucks.

Suppose I am developing a plugin and it has a filter, and I need to make sure that my filter gets executed before, or after, the same filter from another plugin.
How do I enforce that?

I don't see this explained anywhere in the documentation.

Most frameworks that implement filters, hooks, event listeners or any similar mechanism, provide a way to set a "priority", or "execution order", for the plugin/filter/whatever, which usually is an integer.

I assume Omeka does the same, but I can't find anything about it in the documentation.

https://omeka.readthedocs.io/en/latest/Tutorials/understandingFilters.html

**Comment by zerocrates** [comment]
> I can't find anything about it in the documentation.
>
> https://omeka.readthedocs.io/en/latest/Tutorials/understandingFilters.html

It's mentioned on the very page you linked to.

**Comment by php4fan** [comment]
Oh, it's under "Using add_filter directly" which I didn't read because I wasn't interested in that method (also I did search for the word "order" and found no match but forgot to search for "priority").

So the **only way** to set a priority is by **using add_filter** directly?? You can't set it using the `$_filters` property??

**Comment by php4fan** [comment]
Also it doesn't say what is the default priority of filters that are added using `$_filters`, so it gives me no clue what priority I should pass to my filter to ensure it comes before or after one belonging to someone else's plugin that uses `$_filters` isntead.
So no, the answer to my question is NOT in the very page I linked to.

**Comment by zerocrates** [comment]
Yes, you must use add_filter to set a priority.

The default priority is 10. This is indicated on the `add_filter` page, which is linked from the "understanding filters" page.

If you feel the need to respond further on this issue or any other, please consider not being a jerk.
