### ISSUE TITLE
Shortcode sort by element broken?

### ISSUE THREAD

**Issue by mebrett** [omeka/Omeka#924]
From [this forum post](https://forum.omeka.org/t/shortcode-sort-not-working-on-simple-page/11737) - sorting using `sort=“Dublin Core,Property”` doesn't seem to be working, with or without DCExtended. Other sorts are applied as normal.

**Comment by zerocrates** [comment]
So we had some back and forth on this... can we reproduce it, or not? Personally I'm not able to.

**Comment by mebrett** [comment]
It's working for me now, which means we need to warn people about the smart quotes in the documentation, I think.
