### ISSUE TITLE
Theme Header Image Alt Text

### ISSUE THREAD

**Issue by hafizchin** [omeka/Omeka#925]
Hi,

Since Omeka is committed to making accessible sites, is it possible to add an "alt" text for the Theme Header Image? Since it's just for aesthetic purposes, a blank alt text will suffice.

Using the w3c validator, i get this error:

![image](https://user-images.githubusercontent.com/6478018/92797423-0dbbdb00-f380-11ea-8570-8f4a87032702.png)

[https://www.w3.org/wiki/HTML/Usage/TextAlternatives](https://www.w3.org/wiki/HTML/Usage/TextAlternatives)

Looking forward to your reply.

Regards,

Mo

**Comment by kimisgold** [comment]
Yes, this is definitely possible. Can you specify which theme
you're referring to?

**Comment by hafizchin** [comment]
Hi Kim!

Thanks for the very quick response, I was thinking, should it be added to `application/libraries/globals.php`?

```
/**
 * Get the theme's header image tag.
 *
 * @package Omeka\Function\View\Head
 * @uses get_theme_option()
 * @return string|null
 */
function theme_header_image()
{
    $headerImage = get_theme_option('Header Image');
    if ($headerImage) {
        $storage = Zend_Registry::get('storage');
        $headerImage = $storage->getUri($storage->getPathByType($headerImage, 'theme_uploads'));
        return '<div id="header-image"><img src="' . $headerImage . '" /></div>';
    }
}
```

**Comment by hafizchin** [comment]
Just to give you context, we are currently using the `berlin` theme.

**Comment by kimisgold** [comment]
We can do that. We'll also include a theme setting for all the themes from
the Omeka Team so that users can provide their own descriptive text.
