### ISSUE TITLE
Testing/feedback on admin theme updates

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#927]
Branch is new-admin-theme

**Comment by mebrett** [comment]
I pulled the branch but I'm seeing a weird combination of the old and new themes. Is it just me?

**Comment by mebrett** [comment]
I'm still working on reviewing the theme in multiple browsers and sizes, but a few issues with text/background color contrast. For reference, I'm using [Colour Contrast Anaylser](https://developer.paciellogroup.com/resources/contrastanalyser/) and [Contrast Ratio](https://contrast-ratio.com/).

Green action buttons - anything where the text is #519E00 and background #EEF6E6 - fail contrast. Large text is “at least 18 point or 14 point bold” and this is 14 but not bold.

Similarly, helper text (anything in italics, hex color gray - for example descriptions of fields on item add or edit pages) only has a contrast ratio of 3.9:1, and fails minimum contrast.

**Comment by zerocrates** [comment]
I'd noted a couple of issues also:

- When the left nav doesn't have space to fit on screen vertically so it disables its `fixed` position following behavior, it's got positioning issues and ends up drawing underneath the top bar, so the first nav entry can't be read.
- Speaking of contrast, disabled submit buttons have very low contrast, though this could be rectified "for free" by changes to the submit buttons generally. (plus of course disabled controls are expected to have somewhat lower contrast)

**Comment by mebrett** [comment]
Kim and I have completed a review (in spreadsheet)
