### ISSUE TITLE
Zend 1 Framework EOL

### ISSUE THREAD

**Issue by mbuechner** [omeka/Omeka#933]
I can't avoid a feeling of unease that Omeka's still using Zend 1. Are there any plans to switch to Zend 2 or 3 in future?

**Comment by mbuechner** [comment]
I can't avoid a feeling of unease that Omeka's still using Zend 1. Are there any plans to switch to Zend 2 or 3 in future?

**Comment by Daniel-KM** [comment]
If you want to use Zend 3, use Omeka S: this is the main technical difference between them. 

And Omeka S is as simple as Omeka 2 to use, but can do a lot more. Furthermore, most of the plugins are now available on Omeka S, so there is no reason to stay on Omeka Classic, except to maintain old sites (and this is something that is important for an heritage application).

**Comment by mbuechner** [comment]
Thanks, @Daniel-KM! With other words Omeka is discontinued. Is that correct? I read Issue https://github.com/omeka/Omeka/issues/720 where @sharonmleon wrote:
> We've made very public promises to users and funders that we will maintain it as an ongoing concern and we will honor those promises.

So, replacing Zend 1 (EOL four years ago!) is not a part of this promise?

**Comment by sharonmleon** [comment]
Omeka Classis is not discontinued. We maintain the portions of Zend 1 that we ship with Omeka Classic and will continue to do so, the end of life issue is not something to worry about. We took on the responsibility of assuring that those elements of the application are viable and stable.

**Comment by Daniel-KM** [comment]
If the other main point to maintain Omeka Classic (the important first is to maintain old installs) is related to the simplicity for novices, so the right way to manage this case is to create a simplified admin interface for Omeka S, that looks like Omeka Classic, so users will have a little greater simplicity, but a lot more power and standardized data.

**Comment by sharonmleon** [comment]
There is an entire, thriving hosted infrastructure that depends on Omeka Classic: https://Omeka.net/

**Comment by mbuechner** [comment]
Thank you very much, @sharonmleon, for your statement!
