### ISSUE TITLE
Division blocks

### ISSUE THREAD

**Issue by tedi00** [omeka/Omeka#937]
Division blocks do not retain type and tag radio button values after being saved. 
![image](https://user-images.githubusercontent.com/29501342/109479462-b0752c80-7a7a-11eb-8e0c-f6832553a97d.png)

**Comment by zerocrates** [comment]
This is the issue tracker for Omeka Classic.

You're using Omeka S, and I believe your issue is about the external [BlocksPlus module](https://github.com/Daniel-KM/Omeka-S-module-BlockPlus), so issues should be reported there, not here.
