### ISSUE TITLE
Creating and Maintaining Docker Image and K8s cluster Deployment Template

### ISSUE THREAD

**Issue by sunnythepatel** [omeka/Omeka#950]
Hi Team, 
   I  was hoping to maintain and create a docker image and Kubernetes template for the omeka-classic image. I have created a template is there any way I can add or include it over here. Can you please let me know? I have seen the image provided by you on Docker isn't being managed by anyone. 
https://github.com/sunnythepatel/omeka-classic-docker-imange 

Thank you and hope to hear from you.

**Comment by zerocrates** [comment]
Hi,

We've never made any official Docker images. I do seem to remember that someone posted one on Dockerhub and just used the "omeka" name without asking us about it. So that's probably the one you're talking about?

**Comment by sunnythepatel** [comment]
Hi @zerocrates ,
  Thanks for the reply so can I make a docker image and can I maintain it so any user who wants can utilise it as you know it will be useful for folks who want to deploy it in a container or container orchestration like k8s and we can add them in the omeka. Let me know what do you think?

Thank you

**Comment by zerocrates** [comment]
What I guess I don't quite get is what you're asking to do, or asking us to do.

It looks to me like you've already made the images that you're talking about. If it's a question of calling attention to them, we have [the forums](https://forum.omeka.org/c/community-contributions/25) where I'd encourage you to share these.

**Comment by sunnythepatel** [comment]
Hi @zerocrates 
I was hoping that if we can have an official image for omeka that would be great if needed I can maintain.

Thank you

**Comment by zerocrates** [comment]
I'm not sure we're interested in having an "official" image, especially if we're not actually the ones maintaining it.

There's no problem with people sharing theirs, we welcome it in fact, but any "official" status probably goes too far.

**Comment by sunnythepatel** [comment]
Sure @zerocrates  Thanks
