### ISSUE TITLE
Problem with dropdown new css styling

### ISSUE THREAD

**Issue by DBinaghi** [omeka/Omeka#960]
Hello.

Just noticed that the css styling of dropdown fields is causing some graphical problems: the dropdown-arrow picture overlaps field content in cases when the field's width is shorter than the field's text. See example below:

![image](https://user-images.githubusercontent.com/39097246/131806194-db8764cd-a142-401a-9003-b41991452987.png)

Hope this helps.

**Comment by kimisgold** [comment]
Hmm, that shouldn't be happening; the new styles should account for that with right padding. Could you tell me the context for the screenshot and what browser?

**Comment by DBinaghi** [comment]
Hi Kim.
I've noticed the issue in Chrome, latest version (haven't checked with otherb browsers yet); that would be the config page for Facets plugin.
Let me kniw if you need other details.

**Comment by kimisgold** [comment]
I found the style causing the issue, and if you pull the branch's latest changes, it should be fixed.

**Comment by DBinaghi** [comment]
Well done. I confirm the issue is solved now.
