### ISSUE TITLE
Autocomplete background is transparent

### ISSUE THREAD

**Issue by DBinaghi** [omeka/Omeka#962]
Hi.

It seems the new admin theme has got the autocomplete background transparent, so that suggestions are hard to tell from any text in the background (tested with Chrome).

See for instance the Add Tags field in Item/Add:
![image](https://user-images.githubusercontent.com/39097246/131916163-50b77ac3-822f-4a88-8c64-93ae38528db9.png)

Hope this helps.

**Comment by ebellempire** [comment]
I noticed this happening in my plugin too. Not sure what's going on here. Maybe the default jquery-ui styles aren't getting loaded? 

Anyway, if anyone is here looking for a solution for their plugins, I just did this to add a background color.

```
// ...
.autocomplete( "instance" )._renderItem = function( ul, item ) {
  ul.css('background', '#fafafa');
  return jQuery( '<li>' )
    .append( "<span>" + item.label + "</span>" )
    .appendTo( ul );
};
```
I also added some basic styles for the selected item...
```
.ui-state-active,
.ui-state-hover,
.ui-state-focus,
.ui-menu-item:hover,
.ui-menu-item:focus,
.ui-menu-item:active{
  font-weight: 800 !important;
  // ...
}
```
Good enough for now, but maybe not ideal.

**Comment by kimisgold** [comment]
It's now been added to the `new-admin-theme` branch. (https://github.com/omeka/Omeka/commit/79761ebc45d11d1b6c3c4aa11d54cecabf46187f)

**Comment by DBinaghi** [comment]
I can confirm the issue has been solved with last css file change.
Good job.
