### ISSUE TITLE
addElement method messing up with radio button elements' style

### ISSUE THREAD

**Issue by DBinaghi** [omeka/Omeka#970]
Hi.

While working on an update of **AdminImages** plugin, I've noticed there's an issue with the **addElement** method: when adding radio buttons, the styling gets messed up (see attached picture). It seems to be limited to radio buttons, since when replacing `radio` with `select` the alignment is correct.

![Add-Admin-Image-·-Women-Artists-Archive-Miami-·-Omeka-Admin](https://user-images.githubusercontent.com/39097246/139214539-6e2e625a-42c0-4fd3-9777-cf79b853ef8f.png)

The code used, in this case, is:
```
//Upload or URL:
$this->addElement('radio', 'ingest-type', array(
	'label'         => __('Ingest Type'),
	'description'   => __('Please indicate whether you wish to upload an image from your computer or import an image from the internet by its URL.'),
	'order'         => 5,
	'multiOptions'  => array(
		'Upload' => 'Upload',
		'Url' => 'URL'
	)
));
```

Having checked the output code, what's happening with radio buttons is that, while the "label" part of the field gets applied the "two columns alpha" class, the second div is not getting applied the "inputs five columns omega" class, but instead only a "inputs radio" one.

**Comment by zerocrates** [comment]
Is this still a problem? To some extent some of the style changes we've made since this issue might have made it less problematic even while the classes are not applied... but I'm not sure on that.

The issue here is probably with the decorators... I seem to recall for these ones that have multiple inputs we have to have a different set of decorators for them, and we just don't really use radios much of anywhere.

**Comment by DBinaghi** [comment]
The issue is still there, just checked.

In my case, I solved it by using a "select" control instead of a "radio" one, but as radios are standard controls I think it would be nice to have them available too (provided the fix was not taking too much work) - I prefer them for fewer options, as they are more visibily identifiable.

**Comment by zerocrates** [comment]
Looks like this was just a side effect of old code that was intended to _improve_ the radio handling. It should be consistent with other elements after the linked commit.
