### ISSUE TITLE
Core plugin(s) not adapting well to new responsive interface

### ISSUE THREAD

**Issue by DBinaghi** [omeka/Omeka#971]
Hi.
Just noticed that the Simple Pages plugin does not behave as expected (at least, if it was supposed to comply with the new responsive interface). To reproduce issue, go to Simple Pages index page, then click on Add a Page, then reduce viewport size to, say, width = 768px; you'll notice that the "Save" panel does stack below the "Edit" section, but doesn't spread over the whole space available (as opposed to Add Item or Add Collection in main interface).
I guess it's the way the page is built, still if the plugin was adapted to the new Omeka 3.* version that part was probably left behind.
It might be other core plugins have got same issue, haven't checked them yet.
Hope this helps.

**Comment by zerocrates** [comment]
This should be fixed in 3.0.2.
