### ISSUE TITLE
Using addElementToSaveGroup creates visual issue

### ISSUE THREAD

**Issue by DBinaghi** [omeka/Omeka#981]
It seems that following the Best Practices suggestion to use **addElementToSaveGroup** to insert elements in the Save side panel is creating an issue with sizes: **getSaveGroupDefaultElementDecorators** function inserts an extra div (with class=“field”) to contain the button, and the field.input css style cause it to resize width to `calc(5/7 * 100%)`.

As there should be no need to resize buttons or other controls inside the side panels, width should be probably maintained to 100%.

Please see https://forum.omeka.org/t/addelementtosavegroup-creates-visual-issue/15374 for more details.

**Comment by zerocrates** [comment]
This should be fixed on the master branch since the referenced commit.
