### ISSUE TITLE
Specifying type in formInput messes up with control size

### ISSUE THREAD

**Issue by DBinaghi** [omeka/Omeka#982]
Hi.

In a config form (E-mail Notification plugin) I'm using type to specify that the input box should accept only valid e-mail addresses, as follows:

`<?php echo $view->formInput('email_notification_recipient_address', get_option('email_notification_recipient_address'), array('type'=>'email','multiple'=>'multiple')); ?>`

Unfortunately, the use of the type email is messing up with the size of the input box, as visible in this picture (removing the array parameter visually solves the problem, but then make it harder to validate the input box content):
![image](https://user-images.githubusercontent.com/39097246/180196436-61b98f78-9338-4550-a161-5dba61d7d371.png)

**Comment by zerocrates** [comment]
I believe this should have been fixed as of 3.1.2, for the case of `type="email"` (and a couple of others).
