### ISSUE TITLE
Problem with php8.1

### ISSUE THREAD

**Issue by anders-naslund** [omeka/Omeka#986]
Hi,

Just upgrade to PHP 8.1 (php8.0 works fine) and are now facing this issue:
**Error - Zend_Session_Exception**

_Zend_Session::start() - /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Db/Table/Rowset/Abstract.php(Line:368): Error #8192 Return type of Zend_Db_Table_Rowset_Abstract::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice_ 

Zend_Session_Exception: Zend_Session::start() - /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Db/Table/Rowset/Abstract.php(Line:368): Error #8192 Return type of Zend_Db_Table_Rowset_Abstract::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Session.php:509
Stack trace:
#0 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Session/Namespace.php(143): Zend_Session::start()
#1 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Auth/Storage/Session.php(86): Zend_Session_Namespace->__construct()
#2 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Auth.php(91): Zend_Auth_Storage_Session->__construct()
#3 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Auth.php(141): Zend_Auth->getStorage()
#4 /var/www/utv5.kulturhotell.se/web/application/libraries/Omeka/Application/Resource/Currentuser.php(42): Zend_Auth->hasIdentity()
#5 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(695): Omeka_Application_Resource_Currentuser->init()
#6 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(641): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource()
#7 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap()
#8 /var/www/utv5.kulturhotell.se/web/application/libraries/Omeka/Application/Resource/Helpers.php(116): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap()
#9 /var/www/utv5.kulturhotell.se/web/application/libraries/Omeka/Application/Resource/Helpers.php(27): Omeka_Application_Resource_Helpers->_initAclHelper()
#10 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(695): Omeka_Application_Resource_Helpers->init()
#11 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(641): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource()
#12 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap()
#13 /var/www/utv5.kulturhotell.se/web/application/libraries/Omeka/Application/Resource/Frontcontroller.php(63): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap()
#14 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(695): Omeka_Application_Resource_Frontcontroller->init()
#15 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(638): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource()
#16 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap()
#17 /var/www/utv5.kulturhotell.se/web/application/libraries/Zend/Application.php(373): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap()
#18 /var/www/utv5.kulturhotell.se/web/application/libraries/Omeka/Application.php(49): Zend_Application->bootstrap()
#19 /var/www/utv5.kulturhotell.se/web/admin/index.php(28): Omeka_Application->initialize()
#20 {main}

Any insight in what I can do would be appriciated.

/Anders

**Comment by zerocrates** [comment]
There's an incompatibility with the currently-released version and PHP 8.1.

We have fixes implemented in the development code, so the next release of Omeka Classic will be compatible with PHP 8.1.

**Comment by jakeparis** [comment]
Hi @zerocrates do you have a sense for when this compatibility fix will be released?

**Comment by zerocrates** [comment]
Version 3.1 contains the PHP 8.1 compatibility fixes.
